version: '3.9'

services:
  postgres:
    build:
      context: .
      dockerfile: Dockerfile.postgres
    container_name: steam_data
    environment:
      POSTGRES_DB: steam_data  
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 159753
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  python-tests:
    build:
      context: .
      dockerfile: Dockerfile.python
    container_name: bot_tests
    depends_on:
      postgres:
        condition: service_healthy
    command: ["sh", "-c", "sleep 2 && python -m pytest tests/ -v"]